Django/myfirst/myfirst/apps/articles/urls.py
from django.urls import path

from . import views

app_name = "articles"
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:article_id>/', views.detail, name = 'detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name = 'leave_comment'),
    path('<int:article_id>/<int:id>', views.comment_delete, name='comment_delete'),

]

Django/myfirst/myfirst/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('articles.urls')),
    path('articles/', include('articles.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    

]

Django/myfirst/myfirst/apps/articles/models.py
import datetime
from django.db import models

from django.utils import timezone
from django.urls import reverse

class Article(models.Model):
    article_title = models.CharField('название статьи', max_length = 200)
    article_text = models.TextField('текст статьи')
    pub_date = models.DateTimeField('дата публикации')
    '''cat = models.ForeignKey('Comment', on_delete = models.CASCADE, null = True)'''
    def __atr__(self):
        return self.article_title

    def was_published_recenyly(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days = 7))



    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE)
    author_name = models.CharField('имя автора', max_length = 50)
    comment_text = models.TextField('текст коментария', max_length = 200)

    def __atr__(self):
        return self.author_name

def get_absolute_url(self):
    return revers('comment', kwargs={'comment_id': self.pk})

    class Meta:
        verbose_name = 'Коментарий'
        verbose_name_plural = 'Коментарии'

Django/myfirst/myfirst/apps/articles/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render

from django.urls import reverse

from .models import Article
from .models import Comment

def index(request):
    latest_articles_list = Article.objects.order_by('-pub_date')[:5]
    return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list})

def detail(request, article_id):
    try:
        a = Article.objects.get( id = article_id )
    except:
        raise Http404("Статья не найдена")

    latest_comment_list = a.comment_set.order_by('-id')[:10]

    return render(request, 'articles/detail.html', {'article': a, 'latest_comment_list': latest_comment_list})

def leave_comment(request, article_id):

    try:
        a = Article.objects.get( id = article_id )
    except:
        raise Http404("Статья не найдена")
    a.comment_set.create(author_name = request.POST['name'], comment_text = request.POST['text'])

    return HttpResponseRedirect( reverse('articles:detail', args = (a.id,)) )


'''def comment_delete(request, article_id):

    selected_comment = get_object_or_404(Comment, id=id)
    selected_comment.delete()

    return HttpResponseRedirect( reverse('articles:detail', args = (a.id,)) )'''

def comment_delete(request, id, article_id):
    comment = Comment.objects.get(id = id)
    comment.delete()

    return HttpResponseRedirect( reverse('articles:detail', args = (article.id,)) )

Django/myfirst/myfirst/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}

<h2>{{article.article_title}}</h2>

<p>{{article.article_text}}</p>

<em>{{article.pub_date}}</em>

{% if article.was_published_recenyly %}
НОВАЯ СТАТЬЯ
{% endif %}
<hr>

{% if latest_comment_list %}
    {% for c in latest_comment_list %}
        <p>
          <strong>{{c.author_name }} :</strong>
          <strong>{{c.comment_text}}</strong>
        </p>

        <a href="{{ c.id }}" method="POST" onclick="return confirm('Вы уверены, что хотите удалить этот комментарий?')">Удалить</a>


    {% endfor %}

{% else %}
Коментарии не найдены! Станьте первым ;)
{% endif %}

<hr>

<!-- <from action="{% url 'articles:leave_comment' article.id %}" method="POST"> -->
<form action="{% url 'articles:leave_comment' article.id %}" method="POST">
    {% csrf_token %}
    {{ form.name.errors }}
    <input type="text" required placeholder="Ваше имя" name="name" id="name"><br>
    <textarea name="text" required="" placeholder="Текст коментария" rows="10" cols="30" id="text"></textarea><br>
    <input type="submit" value="отправить">

</form>

{% endblock %}

Django/myfirst/myfirst/templates/articles/list.html
{% extends 'base.html '%}

{% block title %}Последние статьи{% endblock %}

{% block content %}

    {% if latest_articles_list %}

        {% for a in latest_articles_list %}
            <a href="{%  url 'articles:detail' a.id %}">{{a.article_title}}</a>

        {% endfor %}

    {% else %}
        Статьи не найдены )=
  {% endif %}



{% endblock %}

Django/myfirst/myfirst/templates/base.html
{% load static %}

<html>
  <head>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">


    <title>{% block title %}МОЙ САЙТ{% endblock %}</title>
  </head>
  <body>
    <div>
            <h1><a href="/">МОЙ САЙТ</a></h1>
        </div>

        {% for post in posts %}
            <div>
                <p>published: {{ post.published_date }}</p>
                <h1><a href="">{{ post.title }}</a></h1>
                <p>{{ post.text|linebreaksbr }}</p>
            </div>
        {% endfor %}
    {% block content %}{% endblock %}
  </body>
</html>